// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {}

declare module '*.wasm' {
	const content: ArrayBuffer;
	export default content;
}
